import { ClientOptions } from "@azure-rest/core-client";

/**
 * GENERATED FILE. DO NOT EDIT DIRECTLY.
 *
 * This file was generated by the exporter helper.
 * To modify this file, use exports.yml and rebuild. Otherwise, your changes will be overwritten on the next build.
 */
export interface OpenAIClientOptions extends ClientOptions {}

export {
  createOpenAI,
  OpenAIContext,
  getEmbeddings,
  getCompletions,
  getChatCompletions,
  getAzureBatchImageGenerationOperationStatus,
  beginAzureBatchImageGeneration,
  listChatCompletions,
  listCompletions,
} from "./customizations/api/index.js";
export { getChatCompletionsWithAzureExtensions } from "./generated/src/api/index.js";
