import { SourceFile, StatementStructures } from "ts-morph";

export interface ExportSource {
  omit?: string[];
  path: string;
}

export interface ParsedExportSource extends ExportSource {
  source: SourceFile;
}

export interface ExportsFileDefinition {
  outputPath: string;
  sources: ExportSource[];
}

export interface ExportsConfiguration {
  esm?: boolean;
  exports: ExportsFileDefinition[];
}

export interface ReferenceLocator {
  symbolName: string;
  sourceFilePath: string;
}

export interface ExportableSymbolCommon {
  name: string;
  structure: StatementStructures;
  references: ReferenceLocator[];
}

export interface DirectExportableSymbol extends ExportableSymbolCommon {
  kind: "directExport";
  sourcePath: string;
}

interface EmittedExportableSymbol extends ExportableSymbolCommon {
  kind: "emit";
}

export type ExportableSymbol = DirectExportableSymbol | EmittedExportableSymbol;

export const EXPORTS_YML = "exports.yml";

export const EXPORTS_FILE_FRONTMATTER = `/**
* GENERATED FILE. DO NOT EDIT DIRECTLY.
*
* This file was generated by the exporter helper.
* To modify this file, use exports.yml and rebuild. Otherwise, your changes will be overwritten on the next build.
*/
`;
